### ISSUE TITLE
General questions bout FontAdaptor

### ISSUE THREAD

**Issue by seekingdeep** [Chuhanxx/FontAdaptor#2]
@Chuhanxx 
- How does it perform against **Arabic and Hebrew** languages, inwhich the text seems **cursive and connected** to each other.
- Why doesn't it create the **glyph line exemplar** by-itself using the training data.
- Should the "glyph line exemplar" be in the same **size and height** of the "text-line to be recognized".
- Can the "exemplar" contain **multiple letters** `oo`, so that if the "text-line to be recognized" contains the word "food" it will recognize the f`oo`d at once.
- Can the "exemplar" contain **words**.
- how does the exemplar affect the **memory usage.**
- Does it accept **multiple** "glyph line exemplar" with **multiple models**, or it should be trained using a **single** "exemplar".
- When wanting to add **new glyphs**, does the model require retraining from **scratch**, or **finetuning** with new "exemplar".

**Comment by Chuhanxx** [comment]
Hi, thank you for tour interest.
1. We have not trained or tested it on Arabic and Hebrew. Connected glyphs may bring difficulties to segmentation: The shape of a certain glyph varies with its adjacent glyphs, making it hard to define a 'global template'. It could be a direction to explore in the future.
2. Training and test glyphs are not always the same, e.g, English in training and Greek in inference. So in this case 'creating the glyph line exemplar by-itself using the training data' is not possible. 
3. No they can be in different size, we resize images to the same height in our experiments for training in batch.
4&5&6. Yes, technically sub-words or words can be used. But the size of sub-words and words is very large in any language, the memory consumption increases linearly with the number of exemplars. I would recommend using the glyphs as exemplars as it solves the problem with minimal cost. 
7. I am not sure what `multiple glyph line exemplar with multiple models'  means, could you explain it further if you don't mind?
8. It does not require any fine-tuning, the model is trained to match novel glyphs it has not seen. When there are new glyphs to be recognized, we just need to provide the new exemplars as input, the model will recognize them by finding the best match.

**Comment by seekingdeep** [comment]
1- Handwriting and cursive ocr is important, because it means that the trained model have formed some sort of understanding of not only the characters, but also of the context.
4- multiple models, have a look at the papers below, they explain creating a voting system using multiple models:
https://arxiv.org/pdf/1807.02004.pdf
https://arxiv.org/pdf/1802.10038.pdf
https://github.com/Calamari-OCR/calamari

0- My concern with this repository is:
- can it handle connected text such as cursive text, handwritten text, arabic, hebrew?
- can it automatically create dictionaries of the glyph, occurrences, context, etc..

anyways, good luck for you

**Comment by Chuhanxx** [comment]
Hi, 
Yes, I agree. This model has learnt to understand the contexts to some extent. However, handwriting and cursive texts are harder tasks because the shape of single glyph changes largely depending on its adjacent glyphs.  In this case, simple segmentation and visual matching is not enough, it raises other questions like how to define a 'global template' for each glyph.

The two question you mentioned are both interesting research questions and potential future work, there is still a lot to explore. Thank you for the discussion and related papers.
