### ISSUE TITLE
the train data download fail

### ISSUE THREAD

**Issue by coldsummerday** [Chuhanxx/FontAdaptor#5]
https://www.robots.ox.ac.uk/~vgg/research/FontAdaptor20/FontSynth_v1.1.tar

You don't have permission to access this resource.

The train data can't download ,so is it others download urls ?

**Comment by Chuhanxx** [comment]
Hi, thank you for pointing it out.  
I have reset the permission, Could you please try again?
Sorry for the inconvenience.
