### ISSUE TITLE
How we can extract these large number of files on the disk?

### ISSUE THREAD

**Issue by zobeirraisi** [Chuhanxx/FontAdaptor#6]
Thanks for your excellent work. Could you please let me know how to extract this huge zip file on my disk? I always get the limit space error while I still have space in my disk? I tried to do it on multiple of my devices, but still, I get a similar error?

**Comment by Chuhanxx** [comment]
Hi, 
The size of dataset is 16GB.
When there is enough space in your disk,  please try `tar -xvf FontSynth_v1.1.tar` to unzip the file.
